### ISSUE TITLE
Disallow ../ in filename. And other things

### ISSUE THREAD

**Issue by Ericy1** [RiceComp413-Fall2022/S4#6]
1. We allow bob..ads
2. We do not allow bob../ads
3. We allow bob1/bob (as long as bob1 is a directory)

Add more cases as necessary

**Comment by john-shieh** [comment]
![IMG_6757](https://user-images.githubusercontent.com/16311525/191607830-08d36b85-3ec3-4b1f-9c2c-255889561147.jpg)

**Comment by gavin2059** [comment]
closed with PR https://github.com/RiceComp413-Fall2022/S4/pull/7
